# These are supported funding model platforms

github: ooples
patreon: cheatcountry
open_collective: # Replace with a single Open Collective username
ko_fi: cheatcountry
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: cheatcountry
issuehunt: ooples
otechie: cheatcountry
custom: ["https://www.paypal.me/cheatcountry", "https://www.buymeacoffee.com/cheatcountry"]
